### ISSUE TITLE
The Link in the README is mistaken.

### ISSUE THREAD

**Issue by migarabhanu** [MinulSandith/ChatterVia#1]
**Well done !**

However, The Link that [you ](@MinulSandith )have mentioned in your [README](https://github.com/MinulSandith/ChatterVia/blob/main/README.md) is mistaken. The link [you](@MinulSandith ) have mentioned directs to an [Text Encrypting](https://minulsandith-text-encrypter-frontend-c6u1q8.streamlit.app) website.

This issue is just opened with the intention of supporting your project. 
Thanks.
@migarabhanu

**Comment by MinulSandith** [comment]
Thank you for your comments. **  @migarabhanu ** 

I have corrected the mistaken URL.
[https://minulsandith-chattervia-chat-room-8mfa07.streamlit.app/](https://minulsandith-chattervia-chat-room-8mfa07.streamlit.app/)

Let me know there are any more errors too.
Thanks.
